---
- hosts: all
  become: yes

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Update apt cache
      apt: 
        update_cache: yes 
        cache_valid_time: 3600
  
  tasks: 
    - name: Install Java
      apt:
        name: openjdk-8-jdk
        state: present

    - name: Download Solr.
      get_url:
        url: https://archive.apache.org/dist/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz
        dest: "{{ download_dir}}/solr-{{ solr_version }}.tgz"
        checksum: "{{ solr_checksum }}"

    - name: Expand Solr
      unarchive:
        src: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        dest: "{{ download_dir }}"
        remote_src: true
        creates: "{{ download_dir }}/solr-{{ solr_version }}/README.txt"

    - name: Run Solr installation script
      command: > 
        {{ download_dir }}/solr-{{ solr_version }}/bin/install_solr_service.sh
        {{ download_dir }}/solr-{{ solr_version }}.tgz
        -i /opt
        -d /opt/solr
        -u {{ solr_user }}
        -s solr
        -p {{ solr_port }}
        creates: {{ solr_dir }}/bin/solr
          
    - name: Ensure Solr is started and enabled at boot
      service:
        name: solr
        state: started
        enabled: yes      